### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by dtosato** [zhengchun/Bobo-Browse.Net#10]
Hi all, could you tell me which is the expected date for the first release?
Thanks, 
Diego

**Comment by NightOwl888** [comment]
I am closing this issue now.

I don't plan to officially release this version because the [port of 3.2.0](https://github.com/NightOwl888/BoboBrowse.Net) supersedes this version. Available on [NuGet here](http://www.nuget.org/packages/BoboBrowse.Net.Spring/).

Thanks for all of your hard work @zhengchun and @dtosato.
