### ISSUE TITLE
Generic FacetHandler

### ISSUE THREAD

**Issue by dtosato** [zhengchun/Bobo-Browse.Net#17]
I have just downloaded the last release of Bobo from nuget https://github.com/zhengchun/Bobo-Browse.Net/commit/37a5fa3f9dfa17b3084ac9c1ec135d2457e15f1d and I found that FacetHandler is generic now. So, which is the correct way to transform the following code?

```c#
string[] fields = new string[] { "category", "subcategory", "text", "number", "date", "price" };
FacetHandler categoryFacetHandler = new SimpleFacetHandler("category");
FacetHandler subcategoryFacetHandler = new SimpleFacetHandler("subcategory");
FacetHandler textFacetHandler = new MultiValueFacetHandler("text");
FacetHandler numberFacetHandler = new RangeFacetHandler("number", true);
FacetHandler dateFacetHandler = new RangeFacetHandler("date", true);
FacetHandler priceFacetHandler = new RangeFacetHandler("price", true);

ICollection<FacetHandler> handlerList = new FacetHandler[] { 
			categoryFacetHandler, 
			subcategoryFacetHandler,
			textFacetHandler, 
			numberFacetHandler, 
			dateFacetHandler,
			priceFacetHandler};

BoboIndexReader boboReader = BoboIndexReader.GetInstance(reader, handlerList)
```
The variable `handlerList` seems to accept only `FacetHandler` of the same type (e.g. `FacetHandler<string>`). Is that right? Should I have to use only strings for my handlers?

**Comment by NightOwl888** [comment]
Actually, I decided to start a [new repository for version 3.2.0](https://github.com/NightOwl888/BoboBrowse.Net) to allow @zhengchun to continue pursuing this version (which doesn't correspond to any BoboBrowse version in Java) if that is what he wants to do.

Over there, you can find updated code samples, a [documentation wiki](https://github.com/NightOwl888/BoboBrowse.Net/wiki), and a port of the [CarDemo application](https://github.com/NightOwl888/BoboBrowse.Net/tree/master/src/CarDemo).

As pointed out in the documentation, some refactoring was done to account for differences between Generics in .NET and Java. A new interface IFacetHandler was made specifically so facet handlers can be passed from one place to another without having to refer to the generic type.

So, your sample can be converted as follows:

```c#
string[] fields = new string[] { "category", "subcategory", "text", "number", "date", "price" };
IFacetHandler categoryFacetHandler = new SimpleFacetHandler("category");
IFacetHandler subcategoryFacetHandler = new SimpleFacetHandler("subcategory");
IFacetHandler textFacetHandler = new MultiValueFacetHandler("text");
IFacetHandler numberFacetHandler = new RangeFacetHandler("number", true);
IFacetHandler dateFacetHandler = new RangeFacetHandler("date", true);
IFacetHandler priceFacetHandler = new RangeFacetHandler("price", true);

IEnumerable<IFacetHandler> handlerList = new IFacetHandler[] { 
			categoryFacetHandler, 
			subcategoryFacetHandler,
			textFacetHandler, 
			numberFacetHandler, 
			dateFacetHandler,
			priceFacetHandler};

BoboIndexReader boboReader = BoboIndexReader.GetInstance(reader, handlerList)
```
If you have any other issues about 3.2.0, please open them on the [new repository](https://github.com/NightOwl888/BoboBrowse.Net/issues).

**Comment by dtosato** [comment]
So, now we have 2 porting, right? Is it impossible for you to work together?

**Comment by NightOwl888** [comment]
Sorry for the confusion. Let me explain what happened here. 

I started looking into why the unit tests were failing, and realized that there were many that were passing that shouldn't have been. When I ported the tests from 2.x they were using version 2.x of Lucene. However, version 3.0.3 of Lucene has added another value to the SortField class to indicate the data type of the sort. I guessed that it was string.

```c#
// NOTE: Added string sorting for lack of a better option - not sure what the default in lucene was 
br.AddSortField(new SortField("date", SortField.STRING, false)); 
```
After looking at the test code in BoboBrowse 3.1.0, I discovered that most of these were set to SortField.CUSTOM instead of SortField.STRING. When I changed them, it threw an exception because the sorting code that was one of the features added in 3.x was missing from this version.

So, the next logical step was to start porting the relevant code from 3.1.0 to make the sorting functionality work. In 3.1.0, 80% of the existing classes changed from 2.x in some really significant way. Unfortunately, the code had changed so significantly, there was no straightforward way to merge the sorting functionality from 3.1.0 into this version.

In the process, I had already converted about 30% of the 3.1.0 code from Java. Also, it was clear that even if I did manage to get the sorting code to work it wasn't going to fix all of the broken tests. So I decided rather than doing the complex analysis and design work it would take to work out how to add the missing pieces to this version, to continue down the path I was already on and port the rest of 3.1.0 from Java. Later I discovered that 3.2.0 was the highest version compatible with Lucene 3.x (previously I thought it was an upgrade to Lucene 4.x), so I upgraded the port to that version.

@zhengchun  had already previously expressed that he didn't want to manage the build process. So, I took it upon myself to create a new repository that I control so as not to step all over his work. He is welcome to use 3.2.0 if he wants to, or he can continue using this version. He is also welcome to contribute - I am guessing that some of the documentation for BoboBrowse is only available in Chinese and if he could translate it to English and/or add Chinese documentation to the 3.2.0 version, that would be great. To be clear, this version is a port of BoboBrowse.Net 2.x that was upgraded to use Lucene.Net 3.0.3 - it is an invention of something new that didn't exist in Java, not a port. I just didn't see much point in inventing something new when there is already a version in Java that is compatible with Lucene.Net 3.0.3 that could be ported in less time than it would take to fix this version. There were a few features that were dropped in 3.2.0 from 2.x, but there are also a lot of new features that were added (there is more than double the amount of code).

Frankly, I think the best option for the BoboBrowse.Net community would be to put the 3.2.0 code back into the CodePlex repository, but I was unable to get any cooperation on that front. After pleading with Alexey for several months to get his version on NuGet and several more months to put this version on CodePlex, I am through wasting time trying to get that done.

So, in short:

- [2.x on CodePlex](https://bobo.codeplex.com/) is compatible with Lucene.Net 2.x, and to the best of my knowledge is stable, but none of the existing unit tests were ported from Java, and it is not available on NuGet. That version corresponds to some 2.x version of BoboBrowse in Java prior to 2.1.
- This version is 2.x, which has been upgraded to be compatible with Lucene.Net 3.0.3 and has some failing unit tests that will take some work to get passing. If @zhengchun can make it into something stable, I will be happy to put it on NuGet. This version doesn't correspond to anything that exists in Java.
- [3.2.0 on GitHub](https://github.com/NightOwl888/BoboBrowse.Net) is compatible with Lucene.Net 3.0.3. All unit tests are passing. Aside from some refactoring to account for differences in compiler features of .NET and Java, it corresponds to version 3.2.0 in Java. Furthermore, I plan to port the 4.x version when Lucene.Net 4.8 is available and put it on NuGet as well.
